---
- name: Instalacja i konfiguracja klienta LDAP
  hosts: all
  become: true
  tasks:

    - name: Aktualizacja repozytoriów
      apt:
        update_cache: yes

    - name: Instalacja pakietów LDAP
      apt:
        name:
          - ldap-utils
          - libnss-ldap
          - libpam-ldap
          - nslcd
        state: present

    - name: Konfiguracja nsswitch.conf dla LDAP
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^passwd:'
        line: 'passwd:         compat ldap'
      notify:
        - Restartowanie nslcd

    - name: Konfiguracja nsswitch.conf dla grupy LDAP
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^group:'
        line: 'group:          compat ldap'
      notify:
        - Restartowanie nslcd

    - name: Konfiguracja nsswitch.conf dla shadow LDAP
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^shadow:'
        line: 'shadow:         compat ldap'
      notify:
        - Restartowanie nslcd

    - name: Dodanie konfiguracji PAM dla LDAP
      lineinfile:
        path: /etc/pam.d/common-auth
        line: 'auth required pam_ldap.so'
        state: present

    - name: Skonfiguruj plik /etc/ldap.conf
      copy:
        dest: /etc/ldap.conf
        content: |
          host 192.168.250.5         # Adres Twojego serwera LDAP
          base dc=lsmyrak,dc=local   # Podstawowy DN w LDAP
          uri ldap://192.168.250.5    # Protokół i adres serwera LDAP
          ldap_version 3
          binddn cn=admin,dc=lsmyrak,dc=local  # DN użytkownika, który się łączy z serwerem
          bindpw Immolation@138      # Hasło użytkownika LDAP
        mode: '0644'
      notify:
        - Restartowanie nslcd

    - name: Restartowanie nslcd
      systemd:
        name: nslcd
        state: restarted
        enabled: yes

    - name: Sprawdzenie, czy klient LDAP działa
      command: getent passwd
      register: ldap_test
      ignore_errors: yes

    - name: Wyświetlanie wyników testu LDAP
      debug:
        var: ldap_test.stdout
